# Generated by Django 4.2.6 on 2023-10-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibotsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bots',
            name='file',
            field=models.FileField(upload_to='files/<built-in function id>'),
        ),
    ]
