# Generated by Django 4.2.6 on 2023-10-11 13:32

import aibotsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibotsite', '0002_alter_bots_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bots',
            name='file',
            field=models.FileField(upload_to=aibotsite.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='bots',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
