# Generated by Django 4.2.6 on 2023-10-13 07:01

import aibotsite.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibotsite', '0003_alter_bots_file_alter_bots_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bots',
            name='file',
            field=models.FileField(upload_to=aibotsite.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator('.csv')]),
        ),
        migrations.AlterField(
            model_name='bots',
            name='id',
            field=models.AutoField(default=aibotsite.models.get_id, primary_key=True, serialize=False),
        ),
    ]
